* Add your finesim options in this file

.option finesim_mode=spicemd
*.option finesim_mode=promd

* You further play following options to check the accuracy
* and run time differences.

*   .option finesim_model=4
*   .option finesim_speed=0
*   .option finesim_partition=0
*   .option finesim_dvmax=0.02

*   .option finesim_model=3
*   .option finesim_speed=1
*   .option finesim_partition=1
*   .option finesim_dvmax=0.3
